/**
 * E2E tests: FSTS Website Reviews Widget — layout rendering
 *
 * Verifies that the real embed snippet (generated by generateEmbedSnippet from
 * @workspace/embed-widget) renders visible review cards in each of the 5
 * supported layout modes: grid, list, masonry, carousel, slider.
 *
 * Strategy:
 *  - Call the real generateEmbedSnippet to produce the actual widget HTML+JS.
 *  - Wrap it in a minimal HTML page and load it via page.setContent().
 *  - Intercept the fetch call with page.route() and return mock review data.
 *  - Assert layout container and card elements are visible in the DOM.
 *
 * No server, auth, or Clerk setup is required — these are pure DOM tests.
 * Because the test uses the real snippet function, any regression in
 * generateEmbedSnippet (CSS class names, filter logic, script structure) will
 * cause the appropriate assertion to fail here.
 */

import { test, expect } from "@playwright/test";
import { generateEmbedSnippet } from "@workspace/embed-widget";

const CONVEX_HTTP_URL = "http://localhost";
const SLUG = "embed-test";
const MOCK_ENDPOINT = `${CONVEX_HTTP_URL}/api/public/reviews?slug=${SLUG}`;

const MOCK_REVIEWS = {
  reviews: [
    {
      reviewerName: "Alice Johnson",
      rating: 5,
      text: "Absolutely fantastic service. Highly recommended!",
      reviewDate: "2024-06-01T00:00:00.000Z",
      provider: "google",
      pinned: false,
    },
    {
      reviewerName: "Bob Martinez",
      rating: 4,
      text: "Very good experience overall.",
      reviewDate: "2024-05-15T00:00:00.000Z",
      provider: "facebook",
      pinned: true,
    },
    {
      reviewerName: "Carol Smith",
      rating: 5,
      text: "Outstanding quality and attention to detail.",
      reviewDate: "2024-04-20T00:00:00.000Z",
      provider: "yelp",
      pinned: false,
    },
  ],
};

function buildPage(snippet: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Embed Widget Test</title></head>
<body>
${snippet}
</body>
</html>`;
}

const LAYOUTS = ["grid", "list", "masonry", "carousel", "slider"] as const;

for (const layout of LAYOUTS) {
  test(`embed widget renders review cards in ${layout} layout`, async ({ page }) => {
    const snippet = generateEmbedSnippet(CONVEX_HTTP_URL, SLUG, { layout });

    await page.route(MOCK_ENDPOINT, (route) => {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_REVIEWS),
      });
    });

    await page.setContent(buildPage(snippet));

    const container = page.locator(`.fsts-rv-${layout}`);
    await expect(container).toBeVisible({ timeout: 10_000 });

    const cards = container.locator(".fsts-rv-card");
    await expect(cards).toHaveCount(3, { timeout: 10_000 });

    for (let i = 0; i < 3; i++) {
      await expect(cards.nth(i)).toBeVisible();
    }

    const names = container.locator(".fsts-rv-name");
    await expect(names.nth(0)).toHaveText("Alice Johnson");
    await expect(names.nth(1)).toHaveText("Bob Martinez");
    await expect(names.nth(2)).toHaveText("Carol Smith");

    const firstStars = container.locator(".fsts-rv-stars").first();
    await expect(firstStars).toBeVisible();
    const filledStars = firstStars.locator(".fsts-rv-star:not(.empty)");
    await expect(filledStars).toHaveCount(5);
  });
}

test("embed widget filters out reviews below minRating", async ({ page }) => {
  const snippet = generateEmbedSnippet(CONVEX_HTTP_URL, SLUG, {
    layout: "grid",
    minRating: 4,
  });

  const mixed = {
    reviews: [
      {
        reviewerName: "Low Rater",
        rating: 2,
        text: "Not great.",
        reviewDate: "2024-06-01T00:00:00.000Z",
        provider: "google",
        pinned: false,
      },
      {
        reviewerName: "Good Rater",
        rating: 5,
        text: "Excellent!",
        reviewDate: "2024-06-02T00:00:00.000Z",
        provider: "google",
        pinned: false,
      },
    ],
  };

  await page.route(MOCK_ENDPOINT, (route) => {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(mixed),
    });
  });

  await page.setContent(buildPage(snippet));

  const container = page.locator(".fsts-rv-grid");
  await expect(container).toBeVisible({ timeout: 10_000 });

  const cards = container.locator(".fsts-rv-card");
  await expect(cards).toHaveCount(1, { timeout: 10_000 });
  await expect(container.locator(".fsts-rv-name")).toHaveText("Good Rater");
});

test("embed widget shows provider badges on cards", async ({ page }) => {
  const snippet = generateEmbedSnippet(CONVEX_HTTP_URL, SLUG, {
    layout: "list",
    showProviderBadge: true,
  });

  await page.route(MOCK_ENDPOINT, (route) => {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(MOCK_REVIEWS),
    });
  });

  await page.setContent(buildPage(snippet));

  const container = page.locator(".fsts-rv-list");
  await expect(container).toBeVisible({ timeout: 10_000 });

  await expect(container.locator(".fsts-rv-badge.google")).toBeVisible();
  await expect(container.locator(".fsts-rv-badge.facebook")).toBeVisible();
  await expect(container.locator(".fsts-rv-badge.yelp")).toBeVisible();
});

test("embed widget renders nothing when fetch returns empty reviews", async ({ page }) => {
  const snippet = generateEmbedSnippet(CONVEX_HTTP_URL, SLUG, { layout: "grid" });

  await page.route(MOCK_ENDPOINT, (route) => {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ reviews: [] }),
    });
  });

  const responsePromise = page.waitForResponse(MOCK_ENDPOINT, { timeout: 10_000 });
  await page.setContent(buildPage(snippet));
  await responsePromise;

  const widget = page.locator("#fsts-reviews-widget");
  await expect(widget).toBeAttached();

  const container = page.locator(".fsts-rv-grid");
  await expect(container).not.toBeAttached();
});
