const APP_URL = "https://taya-fullstacksolutions.vercel.app/sign-in";
const DEMO_EMAIL = "mailto:amorebey@gmail.com?subject=TAYA%20Demo%20Request";

const featureData = [
  ["Website Management", "Manage approved pages, services, products, FAQs, testimonials and website content without exposing code."],
  ["Forms & Leads", "Capture inquiries, organize submissions and keep lead activity visible from one operational workspace."],
  ["Automation", "Use lifecycle rules to reduce repetitive work around publishing, dates, capacity and status changes."],
  ["Media & Content", "Keep flyers, images, documents and approved digital assets organized for everyday publishing."],
  ["Client Portals", "Give customers secure branded access with role-aware permissions and controlled self-service."],
  ["Analytics & SEO", "Track website health, search readiness and operational performance without leaving the platform."],
];

const pages: Record<string, { eyebrow: string; title: string; intro: string; cards: string[][] }> = {
  "/platform": { eyebrow: "THE TAYA PLATFORM", title: "One operating layer for your website and client workflows.", intro: "TAYA turns website maintenance into governed business operations. Your team gets purpose-built tools while design, code and administrative controls stay protected.", cards: [["Design Lock™","Keep approved layouts, code and brand styling protected."],["Structured CMS","Give users focused controls instead of an unrestricted page builder."],["Multi-site operations","Manage multiple client properties from a consistent system."],["Operational visibility","See activity, content state and workflow status in one place."],["Role-aware access","Match platform access to real responsibilities."],["Admin oversight","Retain recovery, governance and platform-level controls."]] },
  "/website-management": { eyebrow: "WEBSITE MANAGEMENT", title: "Keep websites current without turning clients into developers.", intro: "Clients can update the content they own while TAYA preserves the professional design system and technical foundation.", cards: [["Pages & homepage","Maintain approved homepage and page content."],["Services & products","Manage offerings, pricing details and visibility."],["Navigation","Control approved menu items and ordering."],["FAQs & testimonials","Keep trust-building content accurate and fresh."],["Media & flyers","Upload and publish approved visual assets."],["Design protection","Prevent unauthorized structural or code changes."]] },
  "/client-portals": { eyebrow: "CLIENT PORTALS", title: "Secure, branded self-service for the people you serve.", intro: "TAYA supports controlled client access so customers can interact with the business without exposing internal administration.", cards: [["Role-based access","Show each user only what they are authorized to use."],["Branded experience","Keep the portal aligned to the organization."],["Account controls","Support invitations, access state and administrative oversight."],["Protected data","Keep organization-scoped information separated."],["Operational handoff","Connect portal activity back to business workflows."],["Scalable access","Support growing client and team populations."]] },
  "/forms-leads": { eyebrow: "FORMS & LEADS", title: "Turn website inquiries into organized follow-up.", intro: "Build controlled forms, capture submissions and keep lead activity connected to the website operation instead of scattered across inboxes.", cards: [["Form builder","Create approved forms for real business use cases."],["Submission review","See incoming responses in a structured workspace."],["Lead visibility","Keep inquiry context available for follow-up."],["Validation","Reduce incomplete or malformed submissions."],["Workflow-ready","Prepare submissions for notifications and handoff."],["Governed publishing","Control which forms are active and public."]] },
  "/media-content": { eyebrow: "MEDIA & CONTENT", title: "A governed media library built for day-to-day publishing.", intro: "Keep website assets organized and reusable while controlling what clients can upload, publish and replace.", cards: [["Image library","Organize approved website imagery."],["Flyer publishing","Let clients add current promotional flyers."],["Document storage","Keep public-facing files easy to find."],["Asset status","Track what is active and where it is used."],["Safe replacement","Update content without editing site code."],["Admin recovery","Retain higher-level oversight and cleanup tools."]] },
  "/automation": { eyebrow: "AUTOMATION", title: "Let the website respond to dates, capacity and operational state.", intro: "TAYA is built to reduce repetitive cleanup, especially for classes, events and time-sensitive content.", cards: [["Capacity awareness","Help close registration when an offering is full."],["Date awareness","Stop presenting expired events as current."],["Past-event state","Move completed events into historical views."],["Publishing rules","Coordinate active and inactive content states."],["Operational reminders","Support workflows around website upkeep."],["Human oversight","Keep administrators in control of automation behavior."]] },
  "/industries": { eyebrow: "INDUSTRIES", title: "Flexible enough for different organizations. Controlled enough for professional delivery.", intro: "TAYA is designed for businesses that need a polished website plus an operational system behind it.", cards: [["Training & education","Classes, schedules, registrations and content."],["Professional services","Services, inquiries, teams and client access."],["Membership organizations","Updates, resources, events and portals."],["Multi-location businesses","Consistent operations across properties."],["Event-driven organizations","Capacity, dates, flyers and lifecycle state."],["Growing service brands","A scalable website operations foundation."]] },
  "/pricing": { eyebrow: "PRICING", title: "Built around the website operation you actually need.", intro: "TAYA deployments are configured around site scope, users, operational modules and support requirements. We are not publishing placeholder prices before the commercial packaging is finalized.", cards: [["Core website operations","Content, media and controlled website management."],["Client operations","Portal and role-aware access capabilities."],["Automation modules","Lifecycle and workflow features based on need."],["Multi-site deployments","Support for organizations managing multiple properties."],["Implementation","Configuration, onboarding and launch support."],["Talk with FSTS","Request a scope review for current pricing and availability."]] },
  "/about": { eyebrow: "ABOUT TAYA", title: "Website operations designed by Full Stack Tech & Solutions LLC.", intro: "TAYA was created to solve a practical problem: businesses need control over their website content without risking the professional design, code and infrastructure behind it.", cards: [["Business-first","Built around real operational workflows."],["Design-conscious","Protect the quality of professionally delivered websites."],["Governed","Separate everyday access from platform administration."],["Scalable","Support multiple sites, users and changing needs."],["Practical automation","Automate repetitive state changes where useful."],["FSTS platform","Developed and operated by Full Stack Tech & Solutions LLC."]] },
  "/resources": { eyebrow: "RESOURCES", title: "Answers for teams evaluating TAYA.", intro: "Use these quick answers to understand how the platform fits into a website engagement.", cards: [["Can clients change the code?","No. TAYA is designed to give controlled content access without exposing protected code or layouts."],["Can clients upload flyers?","Yes. Approved media and flyer workflows are part of the website operations model."],["Can classes close automatically?","TAYA is being built to use dates and capacity to support automatic closing and past-event transitions."],["Is TAYA multi-site?","Yes. The platform architecture supports management across multiple website properties."],["Is there a client portal?","Yes. Secure portal and account-management capabilities are part of the platform."],["Who operates TAYA?","TAYA is a Full Stack Tech & Solutions LLC platform."]] },
};

function Logo({ light = false }: { light?: boolean }) { return <a className={`brand ${light ? "brand-light" : ""}`} href="/"><img src="/taya-logo.svg" alt="TAYA" /><span>TAYA</span></a>; }

function Header() {
  return <header className="header"><Logo/><nav aria-label="Primary navigation"><a href="/platform">Platform</a><a href="/website-management">Solutions</a><a href="/industries">Industries</a><a href="/pricing">Pricing</a><a href="/resources">Resources</a><a href="/about">About</a></nav><div className="header-actions"><a className="login" href={APP_URL}>Login</a><a className="button button-small gradient" href="/contact">Request Demo →</a></div></header>;
}

function Footer() {
  return <footer><div className="footer-brand"><Logo light/><p className="tagline">Tools. Automation. Your Advantage.</p><p>A Full Stack Tech & Solutions LLC platform for secure website operations and business-ready digital workflows.</p></div><div><b>Platform</b><a href="/platform">Overview</a><a href="/website-management">Website Management</a><a href="/automation">Automation</a><a href="/client-portals">Client Portals</a></div><div><b>Company</b><a href="/about">About</a><a href="/contact">Request Demo</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/accessibility">Accessibility</a></div><small>Copyright © {new Date().getFullYear()} Full Stack Tech & Solutions LLC. All Rights Reserved.</small></footer>;
}

function DashboardVisual() {
  return <div className="visual-wrap" aria-label="TAYA dashboard preview"><div className="blob blob-one"/><div className="blob blob-two"/><div className="laptop"><div className="screen"><aside><div className="mini-brand"><img src="/taya-logo.svg" alt=""/> TAYA</div><strong>Dashboard</strong><span>Websites</span><span>Clients</span><span>Forms & Leads</span><span>Automation</span><span>Media Library</span><span>Analytics</span><span>Settings</span></aside><div className="dash"><div className="dash-title">Dashboard <span>⌕ ◦ ●</span></div><div className="metric-row"><article><small>Active Sites</small><b>248</b><em>+19%</em></article><article><small>Open Leads</small><b>1,842</b><em className="orange">+22%</em></article><article><small>Automations</small><b>86</b><em className="orange">+12%</em></article><article><small>Activity</small><b>24.5K</b><em>+28%</em></article></div><div className="dash-grid"><article><b>Recent Activity</b><p>New form submission</p><p>Website content published</p><p>New client added</p></article><article className="chart"><b>Performance Overview</b><div className="chart-lines">⌁╱╲╱╲╱╱</div></article><article><b>Top Websites</b><p>Current content activity</p><p>Published updates</p><p>Client-managed sites</p></article><article><b>Top Automations</b><p>Welcome workflow</p><p>Lead follow-up</p><p>Event lifecycle</p></article></div></div></div><div className="base"/></div><div className="phone"><div className="phone-top"/><b>Dashboard</b><small>Total Clients</small><strong>248</strong><small>Open Leads</small><strong>1,842</strong><small>Activity</small><strong>24.5K</strong><div className="mini-chart">⌁╱╲╱╱</div></div></div>;
}

function CTA() { return <section className="cta"><div><div className="eyebrow">SEE TAYA IN ACTION</div><h2>Give clients control without giving away the keys to the code.</h2><p>Talk with Full Stack Tech & Solutions LLC about TAYA for your website operations and client workflows.</p></div><a className="button light" href={DEMO_EMAIL}>Request Demo →</a></section>; }

function Home() {
  return <><section className="hero"><div className="hero-copy"><div className="pill">ALL-IN-ONE WEBSITE OPERATIONS PLATFORM</div><h1>Everything You Need<br/>to <span>Grow & Automate</span><br/>Your Business</h1><p>TAYA brings website tools, client operations, forms, content and workflows together — so organizations can save time, work smarter and scale with confidence.</p><div className="actions"><a className="button primary" href="/contact">Request a Demo →</a><a className="button outline" href="/platform">Explore TAYA</a></div><div className="checks"><span>✓ Protected Design</span><span>✓ Controlled Client Access</span><span>✓ Automated Workflows</span></div></div><DashboardVisual/></section><section className="feature-strip">{featureData.map(([title,copy],i)=><article key={title}><span className={`icon i${i}`}>{["▣","◇","✣","▤","♙","▥"][i]}</span><div><b>{title}</b><p>{copy}</p></div></article>)}</section><section className="stats"><article><span>▦</span><div><b>Multi-Site</b><p>Operations ready</p></div></article><article><span>♢</span><div><b>Protected</b><p>Design & code controls</p></div></article><article><span>☆</span><div><b>Structured</b><p>Purpose-built CMS tools</p></div></article><article><span>◉</span><div><b>Connected</b><p>Client workflows</p></div></article></section><section className="section platform"><div><div className="label">ONE OPERATIONAL LAYER</div><h2>Your site stays professionally built. Your team gets safe controls.</h2><p>TAYA separates engineering from daily content operations so teams can keep websites current without breaking the experience.</p><a className="text-link" href="/platform">Explore the platform →</a></div><div className="mini-grid"><article><span>🔒</span><b>Design Lock™</b><p>Protect code, layout and approved styling.</p></article><article><span>▦</span><b>Structured CMS</b><p>Focused controls instead of unrestricted editing.</p></article><article><span>⚡</span><b>Automation</b><p>Rules for dates, capacity and content state.</p></article><article><span>◎</span><b>Multi-Site Ready</b><p>Operate multiple properties consistently.</p></article></div></section><section className="section soft"><div className="label">BUILT FOR REAL OPERATIONS</div><h2>One platform. Many business models.</h2><p className="lead">Designed for organizations that need a great website and a controlled operational system behind it.</p><div className="industry-grid">{["Training & Education","Professional Services","Membership Organizations","Multi-Location Businesses"].map(x=><a href="/industries" key={x}><span>→</span><b>{x}</b></a>)}</div></section><CTA/></>;
}

function StandardPage({ data }: { data: { eyebrow:string; title:string; intro:string; cards:string[][] } }) {
  return <><section className="page-hero"><div className="page-hero-copy"><div className="pill">{data.eyebrow}</div><h1>{data.title}</h1><p>{data.intro}</p><div className="actions"><a className="button primary" href="/contact">Request Demo →</a><a className="button outline" href={APP_URL}>Client Login</a></div></div><div className="page-art"><div className="art-card"><img src="/taya-logo.svg" alt=""/><b>TAYA</b><span>Tools. Automation. Your Advantage.</span></div></div></section><section className="section"><div className="detail-grid">{data.cards.map(([title,copy],i)=><article key={title}><span className={`detail-icon i${i%6}`}>{["◆","▦","✣","◎","◇","▥"][i%6]}</span><h2>{title}</h2><p>{copy}</p></article>)}</div></section><CTA/></>;
}

function Contact() { return <><section className="page-hero compact"><div className="page-hero-copy"><div className="pill">REQUEST A DEMO</div><h1>See how TAYA can fit your website operation.</h1><p>Tell Full Stack Tech & Solutions LLC what you manage today and what your team needs to control. We’ll use that context to scope the right TAYA deployment.</p><div className="actions"><a className="button primary" href={DEMO_EMAIL}>Email Demo Request →</a><a className="button outline" href={APP_URL}>Existing Client Login</a></div></div></section><section className="section"><div className="contact-grid"><article><b>What to include</b><p>Number of websites, key content types, client/team users, forms, events/classes, portal needs and any automation priorities.</p></article><article><b>What happens next</b><p>FSTS reviews the use case, confirms scope and identifies the implementation path before production onboarding.</p></article><article><b>Already using TAYA?</b><p>Use the client login to access the operational dashboard rather than the public marketing website.</p></article></div></section></>; }

const legal: Record<string,{title:string;intro:string;sections:string[][]}> = {
  "/privacy": { title:"Privacy Policy", intro:"This policy explains the general privacy practices for the public TAYA marketing website operated by Full Stack Tech & Solutions LLC.", sections:[["Information we receive","We may receive information you voluntarily provide when requesting a demo or contacting FSTS, such as your name, business information, email address and message."],["Website data","Hosting and security providers may process standard technical information such as IP address, browser data, device information and request logs for delivery, security and reliability."],["How information is used","Information may be used to respond to inquiries, provide requested information, operate and secure the website, improve services and meet legal obligations."],["Sharing","We do not sell personal information. Information may be processed by service providers that support hosting, communications, security or business operations, subject to applicable agreements."],["Retention and security","Information is retained as reasonably necessary for the purpose collected and protected with administrative and technical safeguards appropriate to the service."],["Contact","Privacy questions can be directed to Full Stack Tech & Solutions LLC through the contact information provided on this website."]] },
  "/terms": { title:"Terms & Conditions", intro:"These terms govern use of the public TAYA marketing website. Separate agreements may govern paid TAYA services and customer deployments.", sections:[["Website use","You may use this website for lawful informational and business purposes. Do not misuse, interfere with or attempt unauthorized access to the website or related systems."],["Intellectual property","TAYA™, associated branding, website materials and software are owned by or licensed to Full Stack Tech & Solutions LLC unless otherwise stated."],["No service commitment","Marketing content describes intended platform capabilities and does not replace a signed order, scope of work, subscription agreement or service-level commitment."],["Third-party services","TAYA may reference or integrate third-party providers. Their services are governed by their own terms and availability."],["Disclaimers","The public website is provided on an as-available basis to the extent permitted by law. Specific warranties, support obligations and remedies are defined in applicable customer agreements."],["Changes","FSTS may update these website terms as the platform and legal requirements evolve. Continued use after publication of updates is subject to the revised terms."]] },
  "/accessibility": { title:"Accessibility", intro:"Full Stack Tech & Solutions LLC aims to make the public TAYA marketing website usable by as many people as reasonably possible.", sections:[["Our approach","We design for keyboard access, readable contrast, responsive layouts, semantic structure and meaningful alternative text where applicable."],["Ongoing improvement","Accessibility is reviewed as the website changes. New content and components are expected to follow the same design standards."],["Compatibility","The website is intended to work with current major browsers and common assistive technologies, though combinations of older software may vary."],["Feedback","If you encounter an accessibility barrier, contact FSTS with the page and issue so it can be reviewed."],["Alternative access","If content cannot be accessed in its current format, FSTS can work with you to identify a reasonable alternative method of receiving the information."],["Commitment","Accessibility is part of the site’s ongoing production QA rather than a one-time launch task."]] }
};

function LegalPage({data}:{data:{title:string;intro:string;sections:string[][]}}){return <><section className="legal-hero"><div className="pill">TAYA • FSTS</div><h1>{data.title}</h1><p>{data.intro}</p></section><section className="legal-body">{data.sections.map(([h,p])=><article key={h}><h2>{h}</h2><p>{p}</p></article>)}<p className="legal-note">Last updated: August 31, 2026.</p></section></>}

function NotFound(){return <section className="not-found"><img src="/taya-logo.svg" alt="TAYA"/><div className="pill">404</div><h1>That page isn’t here.</h1><p>Return to the TAYA marketing website or request a demo.</p><div className="actions"><a className="button primary" href="/">Go Home</a><a className="button outline" href="/contact">Request Demo</a></div></section>}

export default function App(){const path=window.location.pathname.replace(/\/$/,"")||"/";let content;if(path==="/")content=<Home/>;else if(path==="/contact")content=<Contact/>;else if(legal[path])content=<LegalPage data={legal[path]}/>;else if(pages[path])content=<StandardPage data={pages[path]}/>;else content=<NotFound/>;return <div className="site"><Header/><main>{content}</main><Footer/></div>}
