// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CoursesListingPage.tsx": () => import("../components/mockups/CoursesListingPage.tsx"),
  "./components/mockups/HomepageCoursesSection.tsx": () => import("../components/mockups/HomepageCoursesSection.tsx")
};
