import { useState } from "react";
import { useSearch, useLocation, Link } from "wouter";
import { AppLayout } from "@/pages/app/SiteDashboard";
import { useQuery, useMutation } from "convex/react";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { Skeleton } from "@/components/ui/skeleton";
import { ModuleAccessDenied } from "@/components/ModuleAccessDenied";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast";
import { AlertTriangle, CalendarDays, Pencil, Plus, Trash2, Users, History } from "lucide-react";
import { VisualEditorShell } from "@/components/VisualEditorShell";
import { PublishValidationModal } from "@/components/PublishValidationModal";
import { ImagePickerField } from "@/components/ImagePickerField";
import { SITE_PRESETS } from "@/config/imagePresets";
import { LifecycleAlertList } from "@/components/LifecycleAlert";
import type { LifecycleAlertType } from "@/components/LifecycleAlert";
import { ClientEmptyState, ClientLoadingList, ClientPageHeader, ClientSection, ClientToolbar } from "@/components/ClientPage";
import { NEARLY_FULL_THRESHOLD, LIFECYCLE_STATUS_LABELS } from "@/lib/constants";
import { formatPrice } from "@/lib/formatPrice";

const EVENT_IMAGE_PRESET = SITE_PRESETS.find((p) => p.label === "Course/Event Thumb");
const COMMON_TIMEZONES = [
  "America/New_York","America/Chicago","America/Denver","America/Los_Angeles","America/Phoenix","America/Anchorage","Pacific/Honolulu","America/Toronto","America/Vancouver","Europe/London","Europe/Paris","Europe/Berlin","Asia/Tokyo","Asia/Shanghai","Australia/Sydney","UTC",
];
const FILTER_TABS = [
  { value: "upcoming", label: "Upcoming" },{ value: "all", label: "All" },{ value: "open-registration", label: "Open Registration" },{ value: "nearly-full", label: "Nearly Full" },{ value: "full", label: "Full" },{ value: "waitlist", label: "Waitlist" },{ value: "in-progress", label: "In Progress" },{ value: "past", label: "Past" },{ value: "cancelled", label: "Cancelled" },{ value: "draft", label: "Draft" },{ value: "archived", label: "Archived" },
] as const;
type FilterValue = (typeof FILTER_TABS)[number]["value"];
function filterEvents(data: any[], filter: FilterValue): any[] {
  switch (filter) {
    case "all": return data;
    case "upcoming": return data.filter((e) => e.status !== "archived" && !["Completed","Cancelled","Archived"].includes(e.lifecycleStatus ?? ""));
    case "open-registration": return data.filter((e) => e.lifecycleStatus === "RegistrationOpen");
    case "nearly-full": return data.filter((e) => e.lifecycleStatus === "NearlyFull");
    case "full": return data.filter((e) => e.lifecycleStatus === "Full");
    case "waitlist": return data.filter((e) => e.lifecycleStatus === "WaitlistOpen");
    case "in-progress": return data.filter((e) => e.lifecycleStatus === "InProgress");
    case "past": return data.filter((e) => e.lifecycleStatus === "Completed");
    case "cancelled": return data.filter((e) => e.lifecycleStatus === "Cancelled");
    case "draft": return data.filter((e) => e.status === "draft");
    case "archived": return data.filter((e) => e.status === "archived" || e.lifecycleStatus === "Archived");
    default: return data;
  }
}
type EventStatus = "draft" | "published" | "archived";
type EventFormState = { title:string; slug:string; status:EventStatus; description:string; startAt:string; endAt:string; location:string; priceCents:string; imageUrl:string; squareItemId:string; capacity:string; waitlistCapacity:string; startDateTime:string; endDateTime:string; registrationOpenAt:string; registrationCloseAt:string; timezone:string; autoCloseRegistration:boolean; autoArchive:boolean; };
function toLocalInput(iso?: string | null): string { if (!iso) return ""; const d=new Date(iso); const pad=(n:number)=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
function toDatetimeLocal(ts?: number | null): string { if (!ts) return ""; const d=new Date(ts); const pad=(n:number)=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
function fromDatetimeLocal(s:string):number|undefined { return s ? new Date(s).getTime() : undefined; }
function toIso(s:string):string|undefined { return s ? new Date(s).toISOString() : undefined; }
const emptyForm: EventFormState = { title:"",slug:"",status:"draft",description:"",startAt:"",endAt:"",location:"",priceCents:"",imageUrl:"",squareItemId:"",capacity:"",waitlistCapacity:"",startDateTime:"",endDateTime:"",registrationOpenAt:"",registrationCloseAt:"",timezone:"America/New_York",autoCloseRegistration:false,autoArchive:false };
function lifecycleBadgeVariant(status:string):"default"|"secondary"|"outline"|"destructive" { switch(status){case "RegistrationOpen":case "NearlyFull":return "default";case "Full":case "Cancelled":case "RegistrationClosed":return "destructive";case "WaitlistOpen":case "Completed":case "Archived":return "secondary";default:return "outline";} }
function statusVariant(status:string){ if(status==="published") return "default"; if(status==="archived") return "secondary"; return "outline"; }
function CapacityBar({entityId,siteId}:{entityId:string;siteId:Id<"sites">}){ const counts=useQuery((api as any).registrations.getCount,{siteId,entityType:"event",entityId}); return counts?(<span className="flex items-center gap-1 text-xs text-slate-500"><Users className="h-3 w-3"/>{counts.confirmedCount}{counts.waitlistCount>0&&<span className="text-amber-600">+{counts.waitlistCount}w</span>}</span>):null; }
function CapacityPanel({entityId,siteId,capacity,waitlistCapacity}:{entityId:string;siteId:Id<"sites">;capacity?:number;waitlistCapacity?:number}){ const counts=useQuery((api as any).registrations.getCount,{siteId,entityType:"event",entityId}); if(!capacity)return null; if(!counts)return <Skeleton className="h-20 w-full rounded-xl"/>; const {confirmedCount,waitlistCount}=counts; const pct=Math.min(100,(confirmedCount/capacity)*100); const nearly=confirmedCount/capacity>=NEARLY_FULL_THRESHOLD; const full=confirmedCount>=capacity; return <div className="space-y-2 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">Registrations</span><span className={`font-semibold ${full?"text-red-600":nearly?"text-amber-600":"text-slate-700"}`}>{confirmedCount} / {capacity}</span></div><Progress value={pct} className={`h-2 ${full?"[&>div]:bg-red-500":nearly?"[&>div]:bg-amber-500":"[&>div]:bg-emerald-500"}`}/>{waitlistCapacity&&waitlistCapacity>0?<p className="text-xs text-slate-500">Waitlist: {waitlistCount} / {waitlistCapacity}</p>:null}</div>; }
function EventAlerts({entity,siteId}:{entity:any;siteId:Id<"sites">}){ const now=Date.now(); const counts=useQuery((api as any).registrations.getCount,{siteId,entityType:"event",entityId:entity._id}); const closingSoon=entity.registrationCloseAt!=null&&entity.registrationCloseAt>now&&entity.registrationCloseAt<=now+86400000; const alerts:Array<{type:LifecycleAlertType;count?:number}|null>=[entity.lifecycleStatus==="Full"?{type:"at_capacity"}:null,entity.lifecycleStatus==="NearlyFull"?{type:"nearly_full"}:null,entity.lifecycleStatus==="RegistrationClosed"?{type:"registration_closed"}:null,entity.lifecycleStatus==="Completed"?{type:"event_passed"}:null,!entity.endDateTime?{type:"missing_end_time"}:null,closingSoon?{type:"registration_closing_soon"}:null,counts&&counts.waitlistCount>0?{type:"waitlist",count:counts.waitlistCount}:null]; return <LifecycleAlertList alerts={alerts}/>; }

export default function EventsList({params}:{params:{siteId:string}}){
  const siteId=params.siteId as Id<"sites">; const {toast}=useToast();
  const data=useQuery(api.events.list,{siteId}); const catalogItems=useQuery(api.square.listCatalogItems,{siteId}); const orphanedEvents=useQuery((api as any).events.listOrphanedCourseSlug,{siteId});
  const createEvent=useMutation(api.events.create); const updateEvent=useMutation(api.events.update); const deleteEvent=useMutation(api.events.remove);
  const search=useSearch(); const [location,navigate]=useLocation(); const activeFilter=(new URLSearchParams(search).get("filter")??"upcoming") as FilterValue;
  function setFilter(f:FilterValue){ const sp=new URLSearchParams(search); if(f==="upcoming")sp.delete("filter");else sp.set("filter",f); const qs=sp.toString(); navigate(location+(qs?`?${qs}`:""),{replace:true} as any); }
  const [dialogOpen,setDialogOpen]=useState(false); const [editing,setEditing]=useState<any|null>(null); const [form,setForm]=useState<EventFormState>(emptyForm); const [deleteTarget,setDeleteTarget]=useState<any|null>(null); const [isPending,setIsPending]=useState(false); const [isDeleting,setIsDeleting]=useState(false); const [validationOpen,setValidationOpen]=useState(false);
  function openCreate(){setEditing(null);setForm(emptyForm);setDialogOpen(true);} function openEdit(ev:any){setEditing(ev);setForm({title:ev.title,slug:ev.slug,status:ev.status,description:ev.description,startAt:toLocalInput(ev.startAt),endAt:toLocalInput(ev.endAt),location:ev.location??"",priceCents:ev.priceCents!=null?String(ev.priceCents):"",imageUrl:ev.imageUrl??"",squareItemId:ev.squareItemId??"",capacity:ev.capacity!=null?String(ev.capacity):"",waitlistCapacity:ev.waitlistCapacity!=null?String(ev.waitlistCapacity):"",startDateTime:toDatetimeLocal(ev.startDateTime),endDateTime:toDatetimeLocal(ev.endDateTime),registrationOpenAt:toDatetimeLocal(ev.registrationOpenAt),registrationCloseAt:toDatetimeLocal(ev.registrationCloseAt),timezone:ev.timezone??"America/New_York",autoCloseRegistration:ev.autoCloseRegistration??false,autoArchive:ev.autoArchive??false});setDialogOpen(true);}
  async function doSave(){setIsPending(true);try{const capacityFields={capacity:form.capacity?parseInt(form.capacity,10):undefined,waitlistCapacity:form.waitlistCapacity?parseInt(form.waitlistCapacity,10):undefined,startDateTime:fromDatetimeLocal(form.startDateTime),endDateTime:fromDatetimeLocal(form.endDateTime),registrationOpenAt:fromDatetimeLocal(form.registrationOpenAt),registrationCloseAt:fromDatetimeLocal(form.registrationCloseAt),timezone:form.timezone||undefined,autoCloseRegistration:form.autoCloseRegistration,autoArchive:form.autoArchive};const startAtIso=toIso(form.startAt);const endAtIso=toIso(form.endAt);if(editing){await updateEvent({siteId,eventId:editing._id,title:form.title,slug:form.slug,status:form.status,description:form.description,startAt:startAtIso,endAt:endAtIso,location:form.location||undefined,priceCents:form.priceCents!==""?parseInt(form.priceCents,10):null,imageUrl:form.imageUrl||undefined,squareItemId:form.squareItemId||undefined,...capacityFields});toast({title:"Event updated"});}else{await createEvent({siteId,title:form.title,slug:form.slug,status:form.status,description:form.description,startAt:startAtIso??form.startAt,endAt:endAtIso,location:form.location||undefined,priceCents:form.priceCents!==""?parseInt(form.priceCents,10):undefined,imageUrl:form.imageUrl||undefined,squareItemId:form.squareItemId||undefined,...capacityFields});toast({title:"Event created"});}setDialogOpen(false);}catch(err){toast({title:"Something went wrong",description:err instanceof Error?err.message:String(err),variant:"destructive"});}finally{setIsPending(false);}}
  async function handleSubmit(e:React.FormEvent){e.preventDefault();if(form.status==="published"){setValidationOpen(true);return;}await doSave();}
  async function confirmDelete(){if(!deleteTarget)return;setIsDeleting(true);try{await deleteEvent({siteId,eventId:deleteTarget._id});toast({title:"Event deleted"});setDeleteTarget(null);}catch(err){toast({title:"Couldn't delete event",description:err instanceof Error?err.message:String(err),variant:"destructive"});}finally{setIsDeleting(false);}}
  const eventValidationData={title:form.title,imageUrl:form.imageUrl||undefined,description:form.description,slug:form.slug}; const filteredData=Array.isArray(data)?filterEvents(data,activeFilter):data;
  return <AppLayout siteId={params.siteId}><VisualEditorShell siteId={siteId} title="Events" subtitle="Create events, control registration windows, track capacity and waitlists." isDirty={false} historyHref={`/app/sites/${siteId}/history`} moduleId="events" previewPath="/events" toolbarActions={<Button onClick={openCreate} size="sm" className="shadow-sm"><Plus className="mr-2 h-4 w-4"/>Add Event</Button>}>
    <ClientPageHeader eyebrow="Scheduling & Registration" title="Events" description="Create events, control registration windows, track capacity and waitlists, and automatically move completed events out of the active schedule." actions={<Button onClick={openCreate} className="shadow-sm"><Plus className="mr-2 h-4 w-4"/>Add Event</Button>} meta={data&&Array.isArray(data)?<span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-500">{data.length} total event{data.length===1?"":"s"}</span>:undefined}/>
    <ClientToolbar>{FILTER_TABS.map((tab)=><button key={tab.value} onClick={()=>setFilter(tab.value)} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold transition-colors ${activeFilter===tab.value?"border-primary bg-primary text-white shadow-sm":"border-transparent bg-slate-50 text-slate-600 hover:border-slate-200 hover:bg-white"}`}>{tab.label}</button>)}</ClientToolbar>
    {orphanedEvents&&orphanedEvents.length>0&&<div className="mb-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600"/><div><p className="font-semibold">Orphaned course link detected</p><p className="mt-1 text-amber-700">{orphanedEvents.length} event{orphanedEvents.length>1?"s":""} reference a course slug that no longer exists.</p><ul className="mt-2 list-disc pl-5 text-xs">{orphanedEvents.map((ev:any)=><li key={ev._id}><strong>{ev.title}</strong> — {ev.courseSlug}</li>)}</ul></div></div>}
    {data===undefined?<ClientLoadingList rows={4}/>:data===null?<ModuleAccessDenied message="Unable to load Events — you may not have access to this site or the events module is disabled."/>:filteredData!.length===0?<ClientSection><ClientEmptyState icon={CalendarDays} title={data.length===0?"No events yet":"No events match this filter"} description={data.length===0?"Add your first event to start publishing schedules and accepting registrations.":"Try another event status or return to the full event list."} action={data.length===0?<Button onClick={openCreate}><Plus className="mr-2 h-4 w-4"/>Add Event</Button>:<Button variant="outline" onClick={()=>setFilter("all")}>View all events</Button>}/></ClientSection>:<ClientSection title="Event Schedule" description={`${filteredData!.length} event${filteredData!.length===1?"":"s"} in this view`}><div className="overflow-x-auto"><table className="min-w-[920px] w-full text-sm"><thead className="border-b border-slate-200 bg-slate-50/80"><tr>{["Title","Status","Lifecycle","Registrations","Price","Starts","Location","Actions"].map((h)=><th key={h} className={`px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500 ${h==="Actions"?"text-right":""}`}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filteredData!.map((ev:any)=><tr key={ev._id} className="transition-colors hover:bg-slate-50/80"><td className="px-4 py-4 font-semibold text-slate-900">{ev.title}</td><td className="px-4 py-4"><Badge variant={statusVariant(ev.status)}>{ev.status}</Badge></td><td className="px-4 py-4">{ev.lifecycleStatus?<Badge variant={lifecycleBadgeVariant(ev.lifecycleStatus)}>{LIFECYCLE_STATUS_LABELS[ev.lifecycleStatus]??ev.lifecycleStatus}</Badge>:<span className="text-xs text-slate-400">—</span>}</td><td className="px-4 py-4">{ev.capacity?<CapacityBar entityId={ev._id} siteId={siteId}/>:<span className="text-xs text-slate-400">Unlimited</span>}</td><td className="px-4 py-4 text-slate-500">{ev.priceCents!=null?formatPrice(ev.priceCents):"Free"}</td><td className="px-4 py-4 whitespace-nowrap text-slate-500">{new Date(ev.startAt).toLocaleString()}</td><td className="px-4 py-4 max-w-44 truncate text-slate-500">{ev.location||"—"}</td><td className="px-4 py-4 text-right"><div className="flex justify-end gap-1"><Button aria-label="Edit" variant="ghost" size="sm" onClick={()=>openEdit(ev)} className="h-8 w-8 p-0"><Pencil className="h-4 w-4"/></Button><Button aria-label="Delete" variant="ghost" size="sm" onClick={()=>setDeleteTarget(ev)} className="h-8 w-8 p-0"><Trash2 className="h-4 w-4 text-red-500"/></Button></div></td></tr>)}</tbody></table></div></ClientSection>}
    </VisualEditorShell>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto rounded-2xl"><DialogHeader className="border-b border-slate-100 pb-4"><DialogTitle className="text-xl">{editing?"Edit Event":"New Event"}</DialogTitle></DialogHeader>{editing&&<EventAlerts entity={editing} siteId={siteId}/>} {editing&&editing.capacity&&<CapacityPanel entityId={editing._id} siteId={siteId} capacity={editing.capacity} waitlistCapacity={editing.waitlistCapacity}/>}<form onSubmit={handleSubmit} className="space-y-5">
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Title</Label><Input aria-label="Title" required value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></div><div className="space-y-1.5"><Label>Web Address</Label><Input aria-label="Web Address" required value={form.slug} onChange={(e)=>setForm({...form,slug:e.target.value})}/></div></div>
      <div className="space-y-1.5"><Label>Description</Label><Textarea aria-label="Description" required rows={4} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Status</Label><Select value={form.status} onValueChange={(v)=>setForm({...form,status:v as EventStatus})}><SelectTrigger aria-label="Status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Draft</SelectItem><SelectItem value="published">Published</SelectItem><SelectItem value="archived">Archived</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>Timezone</Label><Select value={form.timezone} onValueChange={(v)=>setForm({...form,timezone:v})}><SelectTrigger aria-label="Timezone"><SelectValue/></SelectTrigger><SelectContent>{COMMON_TIMEZONES.map((tz)=><SelectItem key={tz} value={tz}>{tz}</SelectItem>)}</SelectContent></Select></div></div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Location</Label><Input aria-label="Location" placeholder="e.g. Main Studio" value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></div><div className="space-y-1.5"><Label>Price (cents)</Label><Input aria-label="Price (cents)" type="number" min={0} placeholder="9900 = $99.00" value={form.priceCents} onChange={(e)=>setForm({...form,priceCents:e.target.value})}/></div></div>
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="mb-3 text-sm font-semibold text-slate-800">Event Date & Time</h3><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Start</Label><Input aria-label="Start" required type="datetime-local" value={form.startAt} onChange={(e)=>setForm({...form,startAt:e.target.value})}/></div><div className="space-y-1.5"><Label>End</Label><Input aria-label="End" type="datetime-local" value={form.endAt} onChange={(e)=>setForm({...form,endAt:e.target.value})}/></div></div></div>
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="mb-3 text-sm font-semibold text-slate-800">Registration Window</h3><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Registration Opens</Label><Input aria-label="Registration Opens" type="datetime-local" value={form.registrationOpenAt} onChange={(e)=>setForm({...form,registrationOpenAt:e.target.value})}/></div><div className="space-y-1.5"><Label>Registration Closes</Label><Input aria-label="Registration Closes" type="datetime-local" value={form.registrationCloseAt} onChange={(e)=>setForm({...form,registrationCloseAt:e.target.value})}/></div></div></div>
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="mb-3 text-sm font-semibold text-slate-800">Capacity & Automation</h3><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Max Capacity</Label><Input aria-label="Max Capacity" type="number" min={1} placeholder="Leave blank for unlimited" value={form.capacity} onChange={(e)=>setForm({...form,capacity:e.target.value})}/></div><div className="space-y-1.5"><Label>Waitlist Capacity</Label><Input aria-label="Waitlist Capacity" type="number" min={0} placeholder="0 = no waitlist" value={form.waitlistCapacity} onChange={(e)=>setForm({...form,waitlistCapacity:e.target.value})}/></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-start gap-2 rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-700"><input type="checkbox" checked={form.autoCloseRegistration} onChange={(e)=>setForm({...form,autoCloseRegistration:e.target.checked})} className="mt-0.5 rounded border-slate-300"/><span><strong className="block text-slate-900">Auto-close registration</strong><span className="text-xs text-slate-500">Close when the event reaches capacity.</span></span></label><label className="flex cursor-pointer items-start gap-2 rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-700"><input type="checkbox" checked={form.autoArchive} onChange={(e)=>setForm({...form,autoArchive:e.target.checked})} className="mt-0.5 rounded border-slate-300"/><span><strong className="block text-slate-900">Auto-archive</strong><span className="text-xs text-slate-500">Move completed events out of the active schedule.</span></span></label></div></div>
      <div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="mb-3 text-sm font-semibold text-slate-800">Media & Integrations</h3><div className="space-y-4"><ImagePickerField siteId={siteId} value={form.imageUrl} onChange={(url)=>setForm({...form,imageUrl:url})} initialPreset={EVENT_IMAGE_PRESET} label="Event Image"/><div className="space-y-1.5"><Label>Square Catalog Item</Label><Select value={form.squareItemId||"__none__"} onValueChange={(v)=>setForm({...form,squareItemId:v==="__none__"?"":v})}><SelectTrigger aria-label="Square Catalog Item"><SelectValue placeholder="Free / not linked"/></SelectTrigger><SelectContent><SelectItem value="__none__">Free / not linked</SelectItem>{(catalogItems??[]).map((item:any)=><SelectItem key={item.squareItemId} value={item.squareItemId}>{item.name}{item.priceCents!=null?` — ${formatPrice(item.priceCents)}`:""}</SelectItem>)}</SelectContent></Select>{(catalogItems??[]).length===0&&<p className="text-xs text-slate-400">No catalog items synced yet. Sync from Commerce → Catalog first.</p>}</div></div></div>
      <DialogFooter className="border-t border-slate-100 pt-4"><Button type="button" variant="outline" onClick={()=>setDialogOpen(false)}>Cancel</Button><Button type="submit" disabled={isPending}>{isPending?"Saving…":"Save Event"}</Button></DialogFooter>
    </form></DialogContent></Dialog>
    <AlertDialog open={!!deleteTarget} onOpenChange={(open)=>!open&&setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete "{deleteTarget?.title}"?</AlertDialogTitle><AlertDialogDescription>This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={confirmDelete} disabled={isDeleting} className="bg-red-600 hover:bg-red-700">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <PublishValidationModal open={validationOpen} onClose={()=>setValidationOpen(false)} onPublish={doSave} data={eventValidationData} title={editing?`Event: ${form.title}`:"New Event"}/>
  </AppLayout>;
}
